version: "2"
linters:
  enable:
    - errorlint
    - misspell
    - revive
    - unconvert
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    revive:
      rules:
        - name: exported
          disabled: true
formatters:
  enable:
    - gofmt
